spring:
  config:
    import:
      - classpath:application.yaml
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:test}
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:password}
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:password}
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update

app:
  jwt:
    key: ${JWT_KEY:secret}
