server:
  forward-headers-strategy: NATIVE
  servlet:
    context-path: /api
    encoding:
      enabled: true
      force: true
      charset: utf-8

spring:
  mvc:
    log-resolved-exception: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

app:
  jwt:
    access-token-expiration-hours: 1
    refresh-token-expiration-hours: 720

springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  api-docs:
    groups:
      enabled: true
  swagger-ui:
    disable-swagger-default-url: true
    display-request-duration: true
    defaultModelsExpandDepth: -1
    groups-order: asc
    tags-sorter: alpha
    operations-sorter: alpha
  cache:
    disabled: true